import type { AppProps } from "next/app";
import Head from "next/head";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { CountsProvider } from "@/lib/counts-context";
import { SettingsProvider } from "@/lib/settings-context";
import { ThemeColorApplier } from "@/components/ThemeColorApplier";
import { ColorModeApplier } from "@/components/ColorModeApplier";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="theme-color" content="#0a0a0a" media="(prefers-color-scheme: dark)" />
        <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)" />
        <meta name="apple-mobile-web-app-title" content="Helm" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.json" />
        <title>Helm</title>
        {/* Favicon is dynamically generated by ThemeColorApplier based on theme color */}
        {/* Apply color mode early to prevent flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var s = JSON.parse(localStorage.getItem('mc_settings') || '{}');
                  var m = s.colorMode || 'dark';
                } catch(e) { var m = 'dark'; }
                var dark = m === 'dark' || (m === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
                if (dark) document.documentElement.classList.add('dark');
                else document.documentElement.classList.remove('dark');
              })();
            `,
          }}
        />
      </Head>
      <ThemeProvider>
        <SettingsProvider>
          <ThemeColorApplier />
          <ColorModeApplier />
          <CountsProvider>
            <Component {...pageProps} />
          </CountsProvider>
        </SettingsProvider>
      </ThemeProvider>
    </>
  );
}
